### ISSUE TITLE
Error on dumps when running docker compose up

### ISSUE THREAD

**Issue by anitacaron** [EBISPOT/scxa_kg#1]
```bash
dumps              | 65000 out of 78394 50.094 sec
dumps              | INFO: A short_form (https://orcid.org/) starts with a digit: orcid_0000_0001_7258_9596 50.112 sec
dumps              | 66000 out of 78394 50.181 sec
dumps              | 67000 out of 78394 50.408 sec
dumps              | 68000 out of 78394 50.515 sec
dumps              | 69000 out of 78394 50.633 sec
dumps              | 70000 out of 78394 50.733 sec
dumps              | 71000 out of 78394 50.839 sec
dumps              | 72000 out of 78394 50.959 sec
dumps              | 73000 out of 78394 51.062 sec
dumps              | 74000 out of 78394 51.211 sec
dumps              | 75000 out of 78394 51.533 sec
dumps              | 76000 out of 78394 51.62 sec
dumps              | Exception in thread "main" java.lang.NumberFormatException: multiple points
dumps              |    at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1914)
dumps              |    at java.base/jdk.internal.math.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
dumps              |    at java.base/java.lang.Float.parseFloat(Float.java:455)
dumps              |    at uk.ac.manchester.cs.owl.owlapi.OWLLiteralImplNoCompression.parseFloat(OWLLiteralImplNoCompression.java:169)
dumps              |    at ebi.spot.neo4j2owl.importer.N2OUtils.extractValueFromOWLAnnotationValue(N2OUtils.java:55)
dumps              |    at ebi.spot.neo4j2owl.importer.N2OOntologyLoader.extractIndividualAnnotations(N2OOntologyLoader.java:157)
dumps              |    at ebi.spot.neo4j2owl.importer.N2OOntologyLoader.extractSignature(N2OOntologyLoader.java:133)
dumps              |    at ebi.spot.neo4j2owl.importer.N2OOntologyLoader.importOntology(N2OOntologyLoader.java:42)
dumps              |    at ebi.spot.neo4j2owl.importer.N2OImportService.prepareCSVFilesForImport(N2OImportService.java:35)
dumps              |    at ebi.spot.neo4j2owl.importer.N2OImporterRunner.main(N2OImporterRunner.java:24)
dumps              | make: *** [Makefile:98: pdb_csvs] Error 1
dumps exited with code 2
Gracefully stopping... (press Ctrl+C again to force)
service "obask-dumps" didn't complete successfully: exit 2
```

What could that be?

**Comment by anitacaron** [comment]
I checked the `composite-metazoan.owl`, which is the only one loaded. I found this number on the property `has component (RO:0002180)`

```xml
<owl:Class rdf:about="http://purl.obolibrary.org/obo/UBERON_0000035">
        <owl:equivalentClass>
            <owl:Class>
                <owl:intersectionOf rdf:parseType="Collection">
                    <rdf:Description rdf:about="http://purl.obolibrary.org/obo/UBERON_0001305"/>
                    <owl:Restriction>
                        <owl:onProperty rdf:resource="http://purl.obolibrary.org/obo/RO_0002180"/>
                        <owl:qualifiedCardinality rdf:datatype="http://www.w3.org/2001/XMLSchema#nonNegativeInteger">1</owl:qualifiedCardinality>
                        <owl:onClass rdf:resource="http://purl.obolibrary.org/obo/UBERON_0005170"/>
                    </owl:Restriction>
                </owl:intersectionOf>
            </owl:Class>
       </owl:equivalentClass>
(...)
</owl:Class>
```

**Comment by anitacaron** [comment]
Actually, the issue is with this annotation

```xml
<ssso-merged-uberon:start_yph rdf:datatype="http://www.w3.org/2001/XMLSchema#float">0.4.0</ssso-merged-uberon:start_yph>
```

**Comment by dosumis** [comment]
- Report on Uberon tracker tagging Damien. 
- Add some custom SPARQL to remove offending axiom for now?

**Comment by anitacaron** [comment]
It's in the developmental stage ontologies repo https://github.com/obophenotype/developmental-stage-ontologies/issues/92

**Comment by anitacaron** [comment]
In the meantime, can we use `composite-metazoan-basic.owl`? I tried it, and it worked.

**Comment by anitacaron** [comment]
This issue was fixed, and will be available in the next Uberon release.
